version: "3.9"
services:
  dev:
    image: devcontainers/oneapi:2025.2.2
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 992
    volumes:
      - ${SOURCE_DIR}:/workspace
      - dev-home:/home/ubuntu
    command: sleep infinity
volumes:
  dev-home:
